import asyncio
import random
import time
import threading
import socket
from flask import Flask
from telethon import TelegramClient, events
from telethon.tl.types import User, Channel, Chat
from telethon.errors import FloodWaitError, RPCError

BOT_CONFIGS = [
    {
        'name': 'lui',
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "7584465421:AAF--_lAY-B-fi4guTeGu9UCkySM06-iCTk",
        'authorized_users': [7520259263],
        'session_name': 'bot1_session'
    },
    {
        'name': 'lui2', 
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "8268820942:AAHzMdvsHg4CZrZRPfEnIBcqynONfpOm7R4",
        'authorized_users': [7520259263],
        'session_name': 'bot2_session'
    },
    {
        'name': 'lui3',
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "8304844305:AAEOzH54evyKwYm14cgF8iRyU6nWVrN7L2U",
        'authorized_users': [7520259263],
        'session_name': 'bot3_session'
    },
    {
        'name': 'lui4',
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "8118282005:AAEadVZ0Qztnsuwud_B_cLIyMDIYFucMiFI",
        'authorized_users': [7520259263],
        'session_name': 'bot4_session'
    },
    {
       'name': 'lui5',
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "7981904030:AAHltrcmEhTBioWSE3NP8NR7IOL5Q6Gf_lE",
        'authorized_users': [7520259263],
        'session_name': 'bot5_session'
    },
    {
       'name': 'lui6',
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "8006748699:AAHd-ovOLNS0aJh9SmxZHKBD5Rxw0dBR0w4",
        'authorized_users': [7520259263],
        'session_name': 'bot6_session'
    },
    {
        'name': 'lui7', 
        'api_id': 23209699,
        'api_hash': "914c6b8aa854364d0f0a7885f53bf595",
        'bot_token': "8275425800:AAHEbY3hJdHL_KTElmmcGREY8KoqvZE_-EU",
        'authorized_users': [7520259263],
        'session_name': 'bot7_session'
    }
]

VZKOU_INSULTS = [ 
        "UR MY BITCH",
    "NIGGA UR A FEMBOY AND A LOSER UR FUCKING ASS UR TRASH AS FUCK UR A LOSER UR A LITTLE FUCKING PEDOPHILE UR FUCKING ASS",
    "UR HEARTBEAT BECOME FASTER IF YOU HEAR MY NAME WHY? FAT ASS GAY",
    "UR LUNGS WILL GET PUNCHED ON AND I WILL SEVERALLY KEEP HOEING U TO DEATH FAGGOT",
    "NIGGAS WILL KILL YOU IN COLD BLOOD FAGGOT",
    "YOUR BONES DECAYED AND ROTTEN TO DEATH",
    "NO WORDS THIS IS MY SLAVES FAT ASS GAY",
    "I AM THE PRODIGY",
    "MY BITCH GOT KNOCKED THE FUCK OUT BY ME",
    "I WILL FUCK U AND TAZE U BITCH ASS FAT ASS GAY",
    "UR LUNGS WILL GET PUNCHED ON AND I WILL SEVERALLY KEEP HOEING U TO DEATH FAGGOT",
    "BITCH ASS FUCKING WHORE",
    "U CANT FIGHT AGAINST ME IM UNSTOPPABLE FAT ASS GAY",
    "OBESE FAGGOT I PUT PRESSURE ON YOU DAILY UR MY FUCKING SON",
    "UR UGLY AS FUCK UR MY BITCH",
    "SUCK UR MOMS PUSSY BITCH FAT ASS GAY",
    "UR WEAK",
    "COME PICK UR DEAD BODY OFF THE TOMBSTONE GARBAGE INFESTED WHORE",
    "U R WASTED GENES FROM DIWATA GET OUT U CRINGE FAT ASS GAY",
    "I WILL TAZE U TO DEATH AND BASH UR HEAD IN WITH A ANVIL",
    "UR OWN DREAM TO MANUAL FASTER THAN EVERYONE AND REACH TIERS GOTTEN CRUSHED BY ME BITCHING YOU BADLY",
    "SLUTTY FUCKING RETARD",
    "SUBHUMAN FUCKING FAGGOT",
    "Y UR FACE LOOKS LIKE OILY DEALDOUGH? FAT ASS GAY",
    "ISOLATED FUCKING LOSER",
    "U R UNEDUCATED AS FUCK U CRINGE DORK FAT ASS GAY",
    "CARVE MY NAME ON UR FUCKING HANDS CUTSLUT",
    "NIGGAS WILL BEAT U TO DEATH AND WONT LOOK BACK AT U",
    "I WILL MAKE U BLEED STARVE AND CRY TO DEATH N SCREAM IN AGONY FAGGOT",
    "MY MERCY HIDES WHEN U R MY OPPONENT FAT ASS GAY",
    "JEWISH COMMUNITYS DONT CLAIM THIS NIGGA",
    "I HAVE NO MERCY FAT ASS GAY",
    "SHUT THE FUCK UP NIGGA YOU HAVE NO RIGHT TO SPEAK UP AGAINST YOUR GOD",
    "NIGGAS WILL DISLOCATE UR JAW EASILY U WONT SURVIVE AFTER I BURN U ALIVE",
    "PUSSY I WILL DESTROY UR CRANIUM",
    "I WILL FUCK U AND TAZE U BITCH ASS FAT ASS GAY",
    "UR A FUCKING FEMBOY FAGGOT",
    "EAT MY SHITTY ON ALSO SUCK MA FUCKING SHOE FAT ASS GAY",
    "GARBAGE ASS TRASH CAN ASS LOSER UR ASS AS FUCK",
    "SHUT THE FUCK UP I BROKE UR FUCKING NECK",
    "UR SLOW AS FUCK",
    "UR MY BITCH NGL UR THE WORST NIGGA I MANUALED",
    "EVERYONE CALLS ME UNHUMAN CUZ MY STRENGTH SO UNSTOPPABLE Y U FIGHT AGAINST ME U UGLY ASS? FAT ASS GAY",
    "MY ACCURACY > URS",
    "FUCK UR BIG BLACK PUSSY FAT ASS GAY",
    "MY TYPING SPEED IS BETTER THAN U COMBINED WITH MY ACCURACY UR SO FUCKING SHIT AND TRASH",
    "GARBAGE ASS NIGGA UR SLOW AS FUCK",
    "THIS IS THE PAIN U WANT RIGHT? REPTILE FAT ASS GAY",
    "I WILL KEEP TERRORIZING YOU FUCK NIGGA",
    "MY BITCH RAN AWAY FROM ME ITS SO BAD HE RAN TO TRYING TO FIGHT ME BACK",
    "BEG FOR FORGIVENESS",
    "U CAN'T DEFEAT MO U POORMAN EVEN THO U CALL UR IDOLS FAT ASS GAY",
    "YOU GOTTEN STABBED MULTIPLE TIMES",
    "UR MENTAL HEALTH IS FUCKED UP YOU NEED HEALTH AID AFTER I GET DONE BRUTALLY HOEING YOU",
    "DRUNK ASS FUCKING LOST TESTOSTERONE FAGGOT SHUT THE FUCK UP OBESE FAGGOT",
    "NIGGA U CANT THINK FOR SHIT UR FUCKING TRASH DEADASS",
    "UNSTABILIZED FUCKING ALZHEIMERS PEDOPHILE FUCKING DIED",
    "I WILL FUCK U AND TAZE U BITCH ASS FAT ASS GAY",
    "UR IN PAIN FROM ME",
    "NIGGAS WILL BEAT U TO DEATH AND WONT LOOK BACK AT U",
    "MY BITCH GOT KNOCKED THE FUCK OUT BY ME",
    "NIGGA UR MY BITCH YOU CANT ACKNOWLEDGE ON HOW TRASH U ARE NIGGA YOU HAVE NO CHANCE OF WINNING BECAUSE I ALWAYS WIN AND I AM ALWAYS RIGHT",
    "NOBODY ELSE WILL FIGHT U SERIOUSLY CUZ UR A TRYING HARD BITCH FAT ASS GAY",
    "UR CORPSE GOTTEN BLEW UP SHUT THE FUCK UP",
    "BEG FOR MERCY",
    "UR FUCKING SHIT",
    "FUCK UR MOMS UGLY BLACK ASS FAT ASS GAY",
    "FIGHT ME BACK UR MY FUCKING BITCH UR SLOW AS FUCK",
    "UR IN PAIN FROM ME",
    "MY BITCH LOST ITS THINKING MID MANUAL LMFAO",
    "UR CORPSE GOTTEN BLEW UP SHUT THE FUCK UP",
    "I DONT ACKNOWLEDGE NIG NOGS LIKE U",
    "ILL PEPPER SPRAY YOU PESTICIDE",
    "UR MY BITCH YOU LEECH OFF ME",
    "WEAK ASS U FUCKING GAY FAT ASS GAY",
    "IM THE ONE WHO GIVES U FUCKING FEAR",
    "NIGGAS WILL MAKE U EAT MOLD OFF THE GROUND SHUT THE FUCK UP",
    "U R BEGGAR BITCH ASS FAT ASS GAY",
    "PARALYZED FUCKING LOSER U DIED TO ME SHUT THE FUCK UP",
    "NIGGA GOT HOED BY LAW AND EXPECTS ME TO GIVE HIM ATTENTION BY HOEING HIM TO DEATH IN A MANUAL JUST FOR HIS DEATHBED TO COME",
    "SHUT THE FUCK UP RETARD",
    "U CRINGE NIGGA JS ADMIT UR DEFEAT FAT ASS GAY",
    "NIGGA THIS IS FINAL DESTINATION FOR YOU ITS UR TURN TO DIE",
    "LOSER ASS FUCK NIGGA",
    "UR VISION GOTTEN BLURRY FROM ME BITCHING U",
    "UR MY BITCH FOR ETERNAL DEADASS UR A DYSLEXIC LOSER UR MALNOURISHED AND HAVE NO ESTROGEN UR FUCKING SLOW",
    "HITLER DISOWNS U FAGGOT",
    "KEEP CLOWNUNG ME U UGLY ASS BUT REMEMBER MY NAME ALWAYS FAT ASS GAY",
    "UR SLOW AS FUCK AND UR MY BITCH I WILL MAKE U SUFFOCATE TO DEATH RETARDED ASS NIGGA",
    "LOSER ASS FUCK NIGGA",
    "WEAK ASS FUCKING SOYBOY PREGNANT TRANSCENDER DIED TO ME",
    "NIGGA MIND IS TWISTED AND IS A FUCKING LOSER YOU ARE TRASH AS FUCK AND IS MY FUCKING BITCH AND IS SLOW AND WEAK AS FUCK BOW DOWN TO ME YOU HAVE NO RIGHT TO EXIST",
    "GO FUCK AND KILL UR SKELETON BODY U R STRUGGLING AGAINST ME DORK FAT ASS GAY",
    "EVERYONE FEARS ME THEY GET IN FEAR WHEN IM IN CHAT",
    "MY BITCH NEEDS A MEDICAL AID TREATMENT",
    "ILL MAKE U SUFFOCATE IN COLD BLOOD",
    "UR BEST WASN'T ENOUGH FOR ME U NIGGA AS FUCK FAT ASS GAY",
    "NIGGAS BRUTALLY STABBED YOU BEHIND UR BACK AND BETRAYED U AND YOU GOT SO HOED BY ME U DECIDED TO KEEP GOING TO REACH UR DEATHBED",
    "I WILL STAB YOU WITH MY KITCHEN KNIFE AND LEAVE U DEAD ON THE BODY WITH NO LIFESPAN",
    "GARBAGE ASS FUCKING CLONE OF ME",
    "UR MY BITCH YOU LEECH OFF ME",
    "ADDICTED DRUG ADDICT",
    "UR VISION GOTTEN BLURRY FROM ME BITCHING U",
    "GARBAGE ASS FUCK NIGGA",
    "UR MY FUCKING SON UR RETARDED",
    "DRUNK ASS FUCKING LOST TESTOSTERONE FAGGOT SHUT THE FUCK UP OBESE FAGGOT",
    "MALNOURISHED ASS FAGGOT U GOT HOED",
    "MY BITCH IS ENRAGED HIS VEINS ARE POPPING OUT AS I AM HOEING HIM",
    "INSECURE INCESTING FAGGOT",
    "UR A FUCKING RODENT",
    "I WILL BRUTALLY MURDER YOU",
    "WEAK ASS FUCKING PARALYZED LOSER DIED TO ME",
    "WEAK ASS FUCKING SOYBOY PREGNANT TRANSCENDER DIED TO ME",
    "U FUCKING SUCK UR MY FUCKING BITCH",
    "I PITY YOU DOG SHIT FUCKING FAGGOT UR SLOW AS FUCK UR UGLY AS FUCK BOW THE FUCK DOWN RIGHT INFRONT OF ME YOU ARE JUST MY SLAVE",
    "UR CORPSE GOTTEN BLEW UP SHUT THE FUCK UP",
    "UR MY DOGGY",
    "I WILL HANG U ON A NAZI FLAG SIGN NIGGA UR FUCKING RETARDED",
    "DEMENTIA PATIENT UR A FUCKING RETARD",
    "UR ON A WORDLIST UR FUCKING TRASH UR MY FUCKING BITCH",
    "UR INFURIATED SHUT THE FUCK UP",
    "ISOLATED DOGGY",
    "UR FUCKING SLOW",
    "STOP GETTING UR LUNCH MONEY STOLEN BY ME",
    "UR MY FUCKING BITCH AND I HOED U",
    "LOSER ASS FUCK NIGGA",
    "YOU GOT FUCKING HOED JUST SHUT THE FUCK UP",
    "MY BITCH NEEDS A MEDICAL AID TREATMENT",
    "UR PERMANENTLY MY FUCKING BITCH",
    "I WILL STAB YOU WITH MY KITCHEN KNIFE AND LEAVE U DEAD ON THE BODY WITH NO LIFESPAN",
    "SHUT THE FUCK UP",
    "UR UGLY AS FUCK AND UR MY BITCH",
    "I PUT TRAUMA ON U UR FUCKING SCARED OF ME",
    "MY BITCH STARTING LEAKING TO DEATH WHILE STARVING AND I STOMPED ON HIS BODY",
    "UR SO FUCKING ASS UR MY FUCKING SON UR WEAK AS FUCK",
    "ADDICTED DRUG ADDICT",
    "HITLER DISOWNS U FAGGOT",
    "YOU HAVE NO ESTROGEN UR MY FUCKING SON",
    "STOP TRYING TO FIGHT BACK UR SO FUCKING ASS UR MY BITCH",
    "UR OVERDOSING SLOWLY ON COCAINE",
    "UR MY BITCH",
    "UR SKIN CELLS WILL BE BURNED TO DEATH WITH OIL FAGGOT",
    "DEMENTIA PATIENT UR A FUCKING RETARD",
    "YOU GOT FUCKING CUCKED BY EVERYONE AND UR MY FUCKING BITCH",
    "NIGGA SHUT THE FUCK UP ILL SLICE UR TONGUE OFF FAGGOT",
    "MY PERSONAL HITMAN WILL COME TO KILL YOU FAGGOT ASS DORK",
    "UR MY BITCH",
    "IM THE FUCKING DISTRIBUTOR THE FASTEST UR SLOW AS FUCK",
    "NIGGA WILL GET REINCARNATED AS MY FUCKING BITCH",
    "UR MENTAL HEALTH IS FUCKED UP YOU NEED HEALTH AID AFTER I GET DONE BRUTALLY HOEING YOU",
    "MY TYPING SPEED IS BETTER THAN U COMBINED WITH MY ACCURACY UR SO FUCKING SHIT AND TRASH",
    "JEWISH COMMUNITYS DONT CLAIM THIS NIGGA",
    "NIGGA I WILL DRINK UR PLASMA BLOOD",
    "MALNOURISHED ASS FAGGOT U GOT HOED",
    "MY BITCH NEEDS A MEDICAL AID TREATMENT",
    "UR ANGRY AS FUCK",
    "I WILL PUT PRESSURE ON UR NECK AND WILL CHOKE U TO DEATH TILL U LOSE OXYGEN SHUT THE FUCK UP SLUT",
    "SHUT THE FUCK UP UR MENTALLY ILL UR RETARDED AS FUCK",
    "UR TO SHIT TO BE A FUCKING DEITY UR TRASH AS FUCK",
    "MY MANUAL SKILLS ARE SO FAST YOU THINK I AUTO BEEF WHEN IN REALITY I AM NUMBER ONE AND MY FUCKING SPEED IS THE FLASH OF FUCKING LIGHT AND IS FASTER THAN THE PEOPLE U ADMIRE EVEN UR OWN PRODIGY SPEED SUCKS ASS UR MY FUCKING BITCH",
    "I AM A VAMPIRE I WILL FUCKING MAKE U BLEED TO DEATH AND TAKE UR SOUL AND MAKE U SOULLESS FAGGOT",
    "UR UGLY AS FUCK",
    "I WILL STAB YOU WITH MY KITCHEN KNIFE AND LEAVE U DEAD ON THE BODY WITH NO LIFESPAN",
    "UR MY FUCKING BITCH MY BABY BROTHER WILL BEAT U UP",
    "MY BITCH HAS A MENTAL BREAKDOWN FROM ME HOEING HIM",
    "MY BITCH GOT HOED SO BADLY THAT HE NEEDS AN MEMORY REFRESHING ITS SO BAD",
    "UR MY BITCH",
    "UR MY FUCKING BITCH AND I HOED U",
    "NIG NOG ASS FUCKING LOSER U DIED TO ME",
    "MY BITCH HAS MEMORY LOSS",
    "LOW TIER ASS FUCKING PRODIGY",
    "UR MY FUCKING DOGGY UR A SLUT",
    "NIGGAS WILL KILL YOU IN COLD BLOOD FAGGOT",
    "MY BITCH GOT KNOCKED THE FUCK OUT BY ME",
    "GARBAGE ASS QUEER FUCKING FAGGOT UR UGLY AS FUCK",
    "I WILL SKIN YOU ALIVE AND GIVE U TRAUMA WHORE",
    "PEDOPHILE U DIED TO ME UR MY FUCKING BITCH",
    "MY BITCH RAN AWAY FROM ME ITS SO BAD HE RAN TO TRYING TO FIGHT ME BACK",
    "NO NAME FUCKING NIG NOG",
    "DEMENTIA PATIENT UR A FUCKING RETARD",
    "MY BITCH IS ENRAGED HE IS DYING TO ME",
    "MY ANTENNA WIRES WILL CHOKE YOU TO DEATH FAGGOT",
    "I WILL SKIN YOU ALIVE AND GIVE U TRAUMA WHORE",
    "NIGGA THIS IS FINAL DESTINATION FOR YOU ITS UR TURN TO DIE",
    "MY BITCH GOT SLAUGHTER TO DEATH",
    "NIGGAS BRUTALLY STABBED YOU BEHIND UR BACK AND BETRAYED U AND YOU GOT SO HOED BY ME U DECIDED TO KEEP GOING TO REACH UR DEATHBED",
    "I STRIKE AND MAKE PEOPLE FEAR WHEN THEY SEE ME SIGHT",
    "IM THE ONE WHO GIVES U FUCKING FEAR",
    "I AM THE DISTRIBUTOR THE FUCKING ONE WHO SHATTERS YOU TO PIECES",
    "SHUT THE FUCK UP BEFORE I COMMIT SEVERAL ARSONS ON YOU PUSSY ASS WHORE",
         "IM THE FUCKING DISTRIBUTOR THE FASTEST UR SLOW AS FUCK",
    "BEG FOR MERCY",
    "I STRANGLED THIS FAGGOT TO DEATH",
    "ISOLATED DOGGY",
    "UR MY FUCKING BITCH",
    "WEAK ASS FUCKING KING REPTILE",
    "UR INFURIATED SHUT THE FUCK UP",
    "I MAKE UR EXISTENCE FEEL QUESTIONED",
    "NIGGAS WILL RIP UR FUCKING HAIR OFF AND MAKE U BEG FOR MERCY",
    "UR UGLY AS FUCK UR MY BITCH",
    "GARBAGE ASS FUCKING CLONE OF ME",
    "MY BITCH IS FUCKING SHAKING TO DEATH HES MY FUCKING BITCH",
    "IM MAXIMUM THREAT TO YOU",
    "YOU GOTTEN STABBED MULTIPLE TIMES",
    "MY BITCH IS LIGHT WORK UR SO FUCKING EASY TO MANUAL AND BEAT ON UR MY FUCKING BITCH UR UGLY AS FUCK MY SON UR UGLY AS FUCK",
    "I AM THE SOUL TAKER THAT FUCKING FIGHTS BACK UR MY FUCKING BITCH",
    "SHUT THE FUCK UP",
    "BLOW UR FUCKING HEAD OFF WITH A M1 GRENADE FUCKING RETARD DEAD PEDOPHILE",
    "UR FUCKING SUCK UR MY FUCKING BITCH",
    "GARBAGE ASS QUEER FUCKING FAGGOT UR UGLY AS FUCK",
    "UR SO FUCKING ASS UR MY SON UR WEAK AS FUCK",
    "DOGGY ASS WHORE DIED TO ME",
    "I HAVE PERSONAL AGENT TO PERSONALLY KILL YOU",
    "UR MY FUCKING BITCH MY BABY BROTHER WILL BEAT UP UR",
    "SHUT THE FUCK UP ILL MURDER YOU IN THE SLUMS",
    "COME PICK UR DEAD BODY OFF THE TOMBSTONE GARBAGE INFESTED WHORE",
    "WE ARE NOT THE SAME UR MY BITCH THATS THE DIFFERENCE BETWEEN US SO STOP TRYING TO SECRETLY COMPARE ME TO U WHEN U CANT COMPREHEND SHIT",
    "MALNOURISHED ASS FAGGOT U GOT HOED",
    "UR MY BITCH YOU GOT HOED",
    "NIGGAS WILL RIP UR FUCKING HAIR OFF AND MAKE U BEG FOR MERCY",
    "LOSER ASS FUCK NIGGA",
    "NIGGA GOT HOED BY LAW AND EXPECTS ME TO GIVE HIM ATTENTION BY HOEING HIM TO DEATH IN A MANUAL JUST FOR HIS DEATHBED TO COME",
    "UR LUNGS WILL GET PUNCHED ON AND I WILL SEVERALLY KEEP HOEING U TO DEATH FAGGOT",
    "IM CRYING UR MY SON",
    "I HAVE PERSONAL AGENT TO PERSONALLY KILL YOU",
    "PUSSY I WILL DISLOCATE UR LIMBS APART FAGGOT",
    "SUICIDAL FUCKING RETARD",
    "I WILL TAZE U TO DEATH AND BASH UR HEAD IN WITH A ANVIL",
    "UR VISION GOTTEN BLURRY FROM ME BITCHING U",
    "GARBAGE ASS NIGGA CANT ESTABLISH SHIT NOR ACCOMPLISH SHIT",
    "YOU GOTTEN STABBED MULTIPLE TIMES",
    "IM VIRTUALLY ABUSING U I PUT TRAUMA IN UR LIFE FAGGOT",
    "SHUT THE FUCK UP",
    "NIGGA UR A FEMBOY AND A LOSER UR FUCKING ASS UR TRASH AS FUCK UR A LOSER UR A LITTLE FUCKING PEDOPHILE UR FUCKING ASS",
    "U LOST UR MIND THINKING IS THIS WHY UR TRASH AT FUCKING MANUAL",
    "I MAKE UR EXISTENCE FEEL QUESTIONED",
    "FIGHT ME BACK UR MY FUCKING BITCH UR SLOW AS FUCK",
    "UR WEAK",
     "I WILL STAB YOU WITH MY KITCHEN KNIFE AND LEAVE U DEAD ON THE BODY WITH NO LIFESPAN",
     "PEDOPHILE U DIED TO ME UR MY FUCKING BITCH"
     "I WILL SHOOT YOU IN A DRIVE BY AND LEAVE U IN CRITIAL CONDITION"
     "SHUT THE FUCK UP",
     "UR MY BITCH",
     "UR SLOW AS FUCK AND UR MY BITCH I WILL MAKE U SUFFOCATE TO DEATH RETARDED ASS NIGGA",
     "PAIN IS WHAT I WILL GIVE U WHORE"
     "MY TYPING SPEED IS BETTER THAN U COMBINED WITH MY ACCURACY UR SO FUCKING SHIT AND TRASH",
     "UR OVERDOSING SLOWLY ON COCAINE",
     "I WILL KEEP TERRORIZING YOU FUCK NIGGA",
     "PRAY FOR ME TO STOP",
     "YOU OVERDOSE DAILY NIGGA SHUT THE FUCK UP UR A DRUG ADDICT UR SLOW AS FUCK",
     "PARALYZED FUCKING LOSER U DIED TO ME SHUT THE FUCK UP NIGGA I WILL DRINK UR PLASMA BLOOD",
     "I CONTROL UR THOUGHTS UR FUCKING RETARDED U INCEL"
     "I PUT FEAR INTO UR HEART",
     "HITLER DISOWNS U FAGGOT",
     "MY ACCURACY > URS",
     "UR MY BITCH YOU LEECH OFF ME",
     "I AM A VAMPIRE I WILL FUCKING MAKE U BLEED TO DEATH AND TAKE UR SOUL AND MAKE U SOULESS FAGGOT",
     "I OWN UR ENTIRE FUCKING BLOODLINE UR MY BITCH",
     "I PUT TRAUMA ON U UR FUCKING SCARED OF ME",
     "ENRAGED FUCKING PEDOPHILE DIED TO ME",
    "NIGGAS WILL DISLOCATE UR JAW EASILY U WONT SURVIVE AFTER I BURN U ALIVE",
     "SHUT THE FUCK UP",
     "PUSSY I WILL DISLOCATE UR LIMBS APART FAGGOT",
     "UR MY FUCKING BITCH U PREY TO ME FAGGOT",
     "YOU HAVE NO ESTROGEN UR MY FUCKING SON",
     "ITS FEAR OR FLIGHT CHOOSE ONE U CHOSEN FEAR OBVIOUSLY BECAUSE UR FUCKING SCARED TO FIGHT BACK",
     "SHUT THE FUCK UP NIGGA YOU HAVE NO RIGHT TO SPEAK UP AGAINST YOUR GOD",
     "I WILL BURN U ALIVE AND TAZE UR DEAD WORTHLESS BODY AFTER NIGGA?",
     "AUTO BEEFING FUCKING LOSER YES U AUTO BEEF AND U WONT PROVE IT TO ME FAGGOT",
     "NIGGA IS SPECTATING HIS DEATH WITH HIS ASS AUTO BEEFER HES MY FUCKING BITCH",
     "WANT ME TO LIGHT UR BODY UP WITH A GASOLINE CAN AND FUCKING BLOW U UP INFLATED FAGGOT?",
     "ILL DIG UR GRAVE FOR U TO BLEED IN IT BITCH ASS FUCKING DORK"
     "SLUTTY FUCKING RETARD",
     "1% NA NGA LANG NG LAKAS KO GINAGAMIT KO SAYO HIRAP KAPA RIN? GANYAN KABA TALAGA KAHINA ASO KO"
     "HOY TABATCHOY NA BISAYA KESA TULUNGAN MO NALANG MAGTANIM NG PALAY SA BUKID MAGULANG MO E MAS NAUNA MO PANG KALABANIN YUNG BOSS MO ASO KO",
     "MALI KA ATA NG NILUGARAN DAPAT NASA BASURAHAN KA NEGRO DI KA BELONG DITO",
    "FLOODED BY LUI",
    "TANGINAMO SOBRANG BOBO",
    "SUMABAY KA TANGA",
    "SUCK MO DICK KO SAGAD",
    "TAE TAE LANG SIGURO LAMAN NG UTAK MO ANG BANTOT BA NAMAN LUMETRA HSHAHAHAA",
    "WALA KA PALA SA AMO MO E KINGINAMO HOY",
    "HOY BOBO FLO FLOOD KITA TANGA",
    "KILALANIN MO BINABANGGA MO BOBO",
    "BOSS MO SI LUI OKIE",
    "TANGINAMO TAMOD KITA",
    "TANGINAMO SASABAY KAPA",
    "WHAHAHAH BAGONG SIBOL KA PALANG FINAL BOSS NA AGAD KINALABAN MO LAIT TULOY NATAMO MO",
    "WHAHAHAHA IYAK DI MAKAISA SI OBESE GOD BA NAMAN KINALABAN NIYA E",
    "ANO PAPALAG KA SA AMO MO",
    "GUSTO MO GAWIN KITANG SEX SLAVE",
    "WALA KA PALA SA BOSS MO E",
    "BROKE BOY KA GAGO",
    "SLAVE LANG KITA WAG KANA UMANGAL",
    "TANGINAMO NIGGA",
    "PAHASA KA MUNA SA MGA KABARO MO BAGO MOKO SUBUKAN NAG MIMISTULANG ANIMAL ABUSING LABAN NATIN DAHIL NAGPAPAKAHAYOP KA E",
    "KAKANTUTIN KO NANAY MONG MALUWAG",
    "TG GUSTO LIGO AYAW? WELL UNDERSTANDABLE NAMAN NA SA ITSURA PA LANG HALATANG MAASIM KANG MATABA KA",
    "BOBO MATULOG KANA",
    "HAHA TANGINAKA SABAYAN HOY",
    "MALAS MO HOY PINANGANAK KA LANG PARA BATUK-BATUKAN RITO SA TG",
    "WALA KA EA MO SAKIN NA",
    "BABOY SPOTTED",
    "ISA KANG BANONG TANGA",
    "ANONG BREED NG ASO KA?",
    "GAME NA BOBO TANGINAMO KAA",
    "WHAHASHAHAHA DI MOKO KAYA MATULOG KA NALANG ATABS",
    "KINGINANG BABOY TO PANO KA TATAGOS E HINDI KA NGA GUMAGAMIT NG UTAK",
    "SUSUBOK KA PA E KITANG KITA NAMAN YUNG AGWAT SA LEVEL NATEN HAHAHAHAA",
    "LUI AMO MO WAG KANA UMANGAL BASURA",
    "AAPAK APAKAN KO LANG PAGKATAO MO HAMPAS LUPA",
    "PALAMUNIN KA LANG TABATCHOY USO EXERCISE",
    "TANGINAMO TAMOD KITA",
    "BUGOK KA TANGA",
    "ISA KANG ALIPIN KO HAHA",
    "WALA KA EA MO SAKIN NA",
    "SLAVE LANG KITA WAG KANA UMANGAL",
    "ANONG BREED NG ASO KA?",
    "ANO PAPALAG KA SA AMO MO",
    "WAG SANA DASHOUT PLS",
    "TG GUSTO LIGO AYAW? WELL UNDERSTANDABLE NAMAN NA SA ITSURA PA LANG HALATANG MAASIM KANG MATABA KA",
    "WAG KA MA STRESS BAKA MANGAYAYAT KA SA SOBRANG TABA MO HAHA",
    "ANO TANGA FLOODED KA NA HAHA",
    "MALI KA ATA NG NILUGARAN DAPAT NASA BASURAHAN KA NEGRO DI KA BELONG DITO",
    "BATUKAN LANG KITA",
    "ISA KANG LOW LEVEL NA TANGA WAG KANANG UMASANG KAYA MOKO HAHAHA",
    "SUMABAY KA TANGA",
    "WELL ANO PA NGA BA AASAHAN KO SAYO MAHIRAP KA NA NGA UNEDUCATED PA BWSHAHAHAQ HAMPAS LUPA",
    "HUMANAP KA NG TALI SABAY BIGTI MO SARILI MO TUTAL WALA KA NAMANG SILBI SA MUNDO",
    "BAGAL MO TANGA",
    "WALA KA TANGA",
    "AHAHAHAHAHAHA KAHIT ILANG HAMPAS LUPA PA NA KAGAYA MO ISAMA MO DI MOKO KAKAYANIN NIGGA",
    "MAGBIGTI KA NALANG KENGKOY PARA MABAWASAN NAMAN YUNG MGA TANGA SA MUNDO",
    "WALA KA PALA SA AMO MO E KINGINAMO HOY",
    "SUSUBOK KA PA E KITANG KITA NAMAN YUNG AGWAT SA LEVEL NATEN HAHAHAHAA",
    "LUI AMO MO WAG KANA UMANGAL BASURA",
    "HSHAHAHA HOYY USO GUMAMIT NG UTAK KUNG MERON KA MAN WAG PURO TANONG KAY CHATGPT KUNG ANONG GAGAWIN RETARDED",
    "LUGI MGA TRANSPORTS SAYO KATUMBAS MO BA NAMAN LAHAT NG TAONG DAPAT SASAKAY KAPAG NARIRIYAN KA E",
    "AAPAK APAKAN KO LANG PAGKATAO MO HAMPAS LUPA",
    "BROKE BOY KA GAGO",
    "KUNG AKO SAYO MAGPAKAMATAY KA NALANG WALA KANG MARARATING HOY PAGIGING PULUBE LANG KABABAGSAKAN MO",
    "WALA KANG SILBI SA MUNDO MAGPAKAMATAY KA NALANG",
    "ANO HAHA",
    "HOY OBESE SAN KA NA",
    "MAG EXERCISE KA NAMAN PARA MABAWASAN FATS NG KATAWAN MO TABATCHOY",
    "BALITA KO LAGI MO RAW INUUBOS MGA ULAM NIYO SA ISANG ARAW AH? MAGTIRA KA NAMAN BABOY",
    "REMEMBER MY NAME TANGA",
    "LUI ON TOP",
    "HSHAHAHAQ TANGINAMO MAHINA LUMAPAG KA NAMAN NAKIKILITI LANG EGO KO SAYONG TANGA KA E",
    "ANO KAYA MO PABA BIGBACK?",
    "NAPAKA BAGAL MO MAG TYPE",
    "KAYA PALA NAPAKA BOBO MO TAGA MINDANAO KA PALA HSHAHAHA",
    "BOBO KA HAHA DI KA TATAGOS",
    "WAG KA DASH OUT HANGGANG UMAGA TAYO DITO",
    "HSHAHAHA ALIPIN LANG KITANG TANGA KA",
    "WHAHAHAHAHA SAN KANA BABOY WALANG WALA NA BA?",
    "ISA KANG LOW LEVEL NA TANGA WAG KANANG UMASANG KAYA MOKO HAHAHA",
    "TANGINAMO SOBRANG BOBO",
    "HAHAHAHA DI NAMAMATAY TONG BOT KO 24/7 TO TANGA WAG KANA UMASA FLOODED KANA BOBO",
    "WALA KA TANGA",
    "KAHIT PITY DI KO NARARAMDAMAN SAYONG HAMPAS LUPA KA NANDIDIRI AKO SAYO",
    "WALA KA PALA SA AMO MO E KINGINAMO HOY",
    "WHAHASHAHAHA DI MOKO KAYA MATULOG KA NALANG ATABS",
    "KAKANTUTIN KO NANAY MONG MALUWAG",
    "SLAVE KITA BANO",
    "BOSS MO SI LUI OKIE",
    "D.O KANA BOBO UNSTOPPABLE TO",
    "BISAKOL PUTANGINAMO",
    "DILAAN MO SAPATOS KO BIGBACK",
    "KUNG AKO SAYO MAGPAKAMATAY KA NALANG WALA KANG MARARATING HOY PAGIGING PULUBE LANG KABABAGSAKAN MO",
    "TANGINAMO NIGGA",
    "SUSUBOK KA PA E KITANG KITA NAMAN YUNG AGWAT SA LEVEL NATEN HAHAHAHAA",
    "BALITA KO LAGI MO RAW INUUBOS MGA ULAM NIYO SA ISANG ARAW AH? MAGTIRA KA NAMAN BABOY",
    "SAN KANA BOBO",
    "PAPALAG KAPANG TANGA KA?",
    "LUI AMO MO WAG KANA UMANGAL BASURA",
    "AAPAK APAKAN KO LANG PAGKATAO MO HAMPAS LUPA",
    "PALAMUNIN KA LANG TABATCHOY USO EXERCISE",
    "TANGINAMO TAMOD KITA",
    "BUGOK KA TANGA",
    "ISA KANG ALIPIN KO HAHA",
    "WALA KA EA MO SAKIN NA",
    "SLAVE LANG KITA WAG KANA UMANGAL",
    "ANONG BREED NG ASO KA?",
    "ANO PAPALAG KA SA AMO MO",
    "WAG SANA DASHOUT PLS",
    "TG GUSTO LIGO AYAW? WELL UNDERSTANDABLE NAMAN NA SA ITSURA PA LANG HALATANG MAASIM KANG MATABA KA",
    "WAG KA MA STRESS BAKA MANGAYAYAT KA SA SOBRANG TABA MO HAHA",
    "ANO TANGA FLOODED KA NA HAHA",
    "MALI KA ATA NG NILUGARAN DAPAT NASA BASURAHAN KA NEGRO DI KA BELONG DITO",
    "BATUKAN LANG KITA",
    "ISA KANG LOW LEVEL NA TANGA WAG KANANG UMASANG KAYA MOKO HAHAHA",
    "SUMABAY KA TANGA",
    "WELL ANO PA NGA BA AASAHAN KO SAYO MAHIRAP KA NA NGA UNEDUCATED PA BWSHAHAHAQ HAMPAS LUPA",
    "HUMANAP KA NG TALI SABAY BIGTI MO SARILI MO TUTAL WALA KA NAMANG SILBI SA MUNDO",
    "BAGAL MO TANGA",
    "WALA KA TANGA",
    "AHAHAHAHAHAHA KAHIT ILANG HAMPAS LUPA PA NA KAGAYA MO ISAMA MO DI MOKO KAKAYANIN NIGGA",
    "MAGBIGTI KA NALANG KENGKOY PARA MABAWASAN NAMAN YUNG MGA TANGA SA MUNDO",
    "WALA KA PALA SA AMO MO E KINGINAMO HOY",
    "SUSUBOK KA PA E KITANG KITA NAMAN YUNG AGWAT SA LEVEL NATEN HAHAHAHAA",
    "LUI AMO MO WAG KANA UMANGAL BASURA",
    "HSHAHAHA HOYY USO GUMAMIT NG UTAK KUNG MERON KA MAN WAG PURO TANONG KAY CHATGPT KUNG ANONG GAGAWIN RETARDED",
    "LUGI MGA TRANSPORTS SAYO KATUMBAS MO BA NAMAN LAHAT NG TAONG DAPAT SASAKAY KAPAG NARIRIYAN KA E",
    "AAPAK APAKAN KO LANG PAGKATAO MO HAMPAS LUPA",
    "BROKE BOY KA GAGO",
    "KUNG AKO SAYO MAGPAKAMATAY KA NALANG WALA KANG MARARATING HOY PAGIGING PULUBE LANG KABABAGSAKAN MO",
    "WALA KANG SILBI SA MUNDO MAGPAKAMATAY KA NALANG",
    "ANO HAHA",
    "HOY OBESE SAN KA NA",
    "MAG EXERCISE KA NAMAN PARA MABAWASAN FATS NG KATAWAN MO TABATCHOY",
    "BALITA KO LAGI MO RAW INUUBOS MGA ULAM NIYO SA ISANG ARAW AH? MAGTIRA KA NAMAN BABOY",
    "REMEMBER MY NAME TANGA",
    "LUI ON TOP",
    "HSHAHAHAQ TANGINAMO MAHINA LUMAPAG KA NAMAN NAKIKILITI LANG EGO KO SAYONG TANGA KA E",
    "ANO KAYA MO PABA BIGBACK?",
    "NAPAKA BAGAL MO MAG TYPE",
    "KAYA PALA NAPAKA BOBO MO TAGA MINDANAO KA PALA HSHAHAHA",
    "BOBO KA HAHA DI KA TATAGOS",
    "WAG KA DASH OUT HANGGANG UMAGA TAYO DITO",
    "HSHAHAHA ALIPIN LANG KITANG TANGA KA",
    "WHAHAHAHAHA SAN KANA BABOY WALANG WALA NA BA?",
    "ISA KANG LOW LEVEL NA TANGA WAG KANANG UMASANG KAYA MOKO HAHAHA",
    "TANGINAMO SOBRANG BOBO",
    "HAHAHAHA DI NAMAMATAY TONG BOT KO 24/7 TO TANGA WAG KANA UMASA FLOODED KANA BOBO",
    "WALA KA TANGA",
    "KAHIT PITY DI KO NARARAMDAMAN SAYONG HAMPAS LUPA KA NANDIDIRI AKO SAYO",
    "WALA KA PALA SA AMO MO E KINGINAMO HOY",
    "WHAHASHAHAHA DI MOKO KAYA MATULOG KA NALANG ATABS",
    "KAKANTUTIN KO NANAY MONG MALUWAG",
    "SLAVE KITA BANO",
    "BOSS MO SI LUI OKIE",
    "D.O KANA BOBO UNSTOPPABLE TO",
    "BISAKOL PUTANGINAMO",
    "DILAAN MO SAPATOS KO BIGBACK",
    "KUNG AKO SAYO MAGPAKAMATAY KA NALANG WALA KANG MARARATING HOY PAGIGING PULUBE LANG KABABAGSAKAN MO",
    "TANGINAMO NIGGA",
    "SUSUBOK KA PA E KITANG KITA NAMAN YUNG AGWAT SA LEVEL NATEN HAHAHAHAA",
    "BALITA KO LAGI MO RAW INUUBOS MGA ULAM NIYO SA ISANG ARAW AH? MAGTIRA KA NAMAN BABOY",
    "SAN KANA BOBO",
    "PAPALAG KAPANG TANGA KA?",
    "SUCK MO DICK KO SAGAD",
    "HAHA TANGINAKA SABAYAN HOY",
    "MAG PAKAMATAY KA NA LANG",
    "D.O KANA BOBO UNSTOPPABLE TO",
    "BAGALAN KO? HAHA",
    "WAG KA D.O HOY",
    "ANO HOY IISA KA",
    "SAY AH LAMUTAKIN MO BURAT KO",
    "SLAVE KITA BANO",
    "BALLISTIC VEST YANG ACNE MO HAHA",
    "T-TYPE KAPA BOBO WAG NA",
    "WAG KA LIHIS SAKEN HAHA",
    "WALA KA TANGA",
    "WALA KANG SILBI",
    "MASARAP BA TITE KO? HAHA",
    "IAN EUT YS",
    "PUTANGINA NAMAN SINAYANG MO ORAS KO",
    "TANDAAN MO SLAVE LANG KITA",
    "SUSUBOK KAPA SA BOSS MO?",
    "READY KA NA BA MAMATAY",
    "HAHAHAHAHAHA",
    "KEEP TRYING",
    "ANO OBESE",
    "RETARD KABA?",
    "BAGAL MO TANGA",
    "GAME NA BOBO TANGINAMO KAA",
    "WALA KA SAKIN GAGO HAHAHAHA",
    "AMBOBO MO E",
    "SISIPAIN KO MUKHA MO EH",
    "READY KA NA BA MAMATAY ",
    "SLAVE LANG KITA TANGINAMO KANG BISUGO KA ",
    "BATA KITA OKIE ",
    "BUGOK KA TANGA ",
    "SAY AH LAMUTAKIN MO BURAT KO ",
    "DILAAN MO SAPATOS KO GAGO ",
    "AKO NASA ITAAS MO ",
    "HINAHATAK LANG KITA SA KAILALIMAN ",
    "NABUGBOG KA TULOY HAHA ",
    "ISA KANG BANONG TANGA ",
    "BANO TANGINAMO LUI ON TOP ",
    "HAWAK KITA SA LEEG ",
    "KALA TALAGA NI TANGA KAYA NYA MAKIPAG SABAYAN SAKIN ",
    "INAAPAK APAKAN KO LANG PAG KA TAO MO ",
    "ISA KANG OILY OBESE ",
    "TANGINAMO KA PALAKAS KAPA SLOW TYPER ",
    "WALA KA TANGA ",
    "SHAHSAHSAH DI MAKASABAY ",
    "LUI AMO MO ",
    "D.O NA SI GAGO ",
    "SUCK MO DICK KO RN ",
    "SA SUSUNOD WAG MOKO GALITIN HA TANGINAKA ",
    "D.O NA YAN SI GAGO?? ",
    "ANO ON TOP KA? SA BURAT KO ",
    "ASPIN LANG KITA HAYUF KA ",
    "ANO NA HOY ",
    "PAKAMATAY KA NALANG PLS ",
    "SEX SLAVE LANG KITA ",
    "BISAKOL PALA TO E ",
    "TANGINAMO MAHINA ",
    "KILALANIN MO BINABANGGA MO BOBO ",
    "TANGINAMO KENGKOY BIGTI KA NALANG ",
    "SUBO MO TITE KO TANGA ",
    "GUSTO MO BA HAMPASIN KO NGALANGALA MO KANG TARANTADO KA? ",
    "ANO PAPALAG KA SA AMO MO ",
    "ASPIN LANG KITA ",
    "HOY DI KO MAKITA CHAT MO HAHA ",
    "MAG PAKAMATAY KA NA LANG ",
    "ANO HOY IISA KA ",
    "PUTANGINA NAMAN SINAYANG MO ORAS KO ",
    "TANGINAMO TAMOD KITA ",
    "WALA KA NIGGA ",
    "LULUMPUHIN KITANG GAGO KA ",
    "ISA KANG UOD NA INAAPAK APAKAN ",
    "REMEMBER MY NAME TANGA ",
    "KALA MO TATAGOS KA SAKEN HAHA ",
    "TANGINAMOKA MAG MUKMOK KA NALANG SA BAHAY NIYO ",
    "PALAG PALAG PALAG ",
    "AKO ANG BOSS AMO MO ",
    "KUNG AKO SAIYO MAG Q-QUIT TG NALANG AKO ",
    "BATUKAN LANG KITA ",
    "ISA KANG MANGMANG ",
    "HOY TABACHOY LAPAG NA ",
    "SUBO MO NA RIN TITE KO BAGAL MO E ",
    "BAWAL MATULOG DITO TANGA ",
    "WAG KANA PUMALAG ",
    "LIGO AYAW PURO SOCIAL MEDIA? ",
    "APAKA BAGAL MO ",
    "TANGINA WALA NA? ",
    "ANTANGA MO ",
    "AMBOBO MO E ",
    "TANGINAMO SAN KANA ",
    "WALA KA TANGA ",
    "WALA KA NAMAN PALA E ",
    "WAG KANA PUMALAG ",
    "SARAP MO BATUKAN ",
    "HAHAHAHA ",
    "SUCK MO DICK KO GAGO FATASS ",
    "FIGHT BACK DORK ",
    "SANAOL WACK ",
    "TANDAAN MO AKO BOSS AMO MO ",
    "HAHA LABAS MO PAGIGING RANTER MO KENGKOY ",
    "KAKATAYIN KO LANG ANG PAMILYA MO ",
    "BROKE BOI WAG KA MAG D.O ",
    "ISA KANG ANIMAL ",
    "TAHOL KA NANG TAHOL ",
    "DI KA MANANALO SAKEN KENGKOY ",
    "PAPALAG KAPANG TANGA KA? ",
    "GANITO BA PAG MALAKAS?? HAHA ",
    "WAG KA DASH OUT HANGGANG UMAGA TAYO DITO ",
    "TANGINAMO BADING ",
    "BOBO DI MO AKO KAYA LUI ON TOP ",
    "KUNG AKO SAIYO MAG Q-QUIT TG NALANG AKO ",
    "ANO TANGA KAYA MO PA? ",
    "DI MAKAISA ",
    "HOY TABA GISING NA ",
    "TANGINAMO SOBRANG BOBO ",
    "ISA KANG BOBO ",
    "BANO KA TALAGA EH AHHAH ",
    "TANGINAMOKA KALA MO MAKAKA SABAY KA SAKEN? ",
    "BOBO ",
    "HOY BOBO FLO FLOOD KITA TANGA ",
    "ISA KANG UOD NA INAAPAK APAKAN ",
    "GUSTO MO BA HAMPASIN KO NGALANGALA MO KANG TARANTADO KA? ",
    "BISAKOL PUTANGINAMO ",
    "LAMUTAKIN MO BAYAG KO ",
    "SUCK MO DICK KO RN ",
    "SABAY NAMAN SANA JAN HOY ",
    "ISA KANG BANONG TANGA ",
    "WAG KA LILIHIS HAHA ",
    "SUCK MO DICK KO GAGO FATASS ",
    "HOY TABA GISING NA ",
    "BISAKOL PUTANGINAMO ",
    "SIGBIN SPOTTED ",
    "BATA KITA OKIE ",
    "GANITO BA PAG MALAKAS?? HAHA ",
    "WALA KA PALA SA AMO MO E ",
    "LIGO AYAW PURO SOCIAL MEDIA? ",
    "ANO NA TANGINAMOKA SLAVE ",
    "ANONG BREED NG ASO KA? ",
    "HOY TANGA LUMAPAG KA HAHA ",
    "FLOODED BY LUI ",
    "GUSTO MO NG SKINCARE BROKEBOY? HAHA ",
    "TANGINAMOKA KALA MO MAKAKA SABAY KA SAKEN? ",
    "SUSUBOK KAPA SA BOSS MO? ",
    "DILAAN MO SAPATOS KO GAGO ",
    "SUMABAY KA TANGA ",
    "CUTE MO TABACHOY ",
    "TANGINAMO NIGGA ",
    "LUI ON TOP KING INA KA ",
    "SUCK MO DICK KO SAGAD ",
    "NICE TRY PILIIN MO KINAKALABAN MO TANGA ",
    "TAHOL KA NANG TAHOL ",
    "BOBO MATULOG KANA ",
    "DI KO MAKITA CHAT MO MB ",
    "BOBO DI MO AKO KAYA LUI ON TOP ",
    "WALA KA NAMAN PALA E ",
    "TANGINAMO KENGKOY BIGTI KA NALANG ",
    "KAYA MO BA AKO SABAYAN? ",
    "TANDAAN MO AKO BOSS AMO MO ",
    "D.O NA YAN SI GAGO?? ",
    "TANGINAMO SASABAY KAPA ",
    "DI MAKAISA ",
    "TANGINAMO TAMOD KITA ",
    "NICE TRY PILIIN MO KINAKALABAN MO TANGA ",
    "WAG KA D.O HOY ",
    "GUSTO MO GAWIN KITANG SEX SLAVE ",
    "D.O NA SI GAGO ",
    "SARAP MO BATUKAN ",
    "PAPALAG KAPANG TANGA KA? ",
    "AKO NASA ITAAS MO ",
    "NAPAKA BAGAL MO MAG TYPE ",
    "TANGINAMO SAN KANA ",
    "LUI AMO MO ",
    "ANONG BREED NG ASO KA? ",
    "FIGHT BACK DORK ",
    "WALA KA NIGGA ",
    "BAWAL MATULOG DITO TANGA ",
    "TANGINAMOKA MAG MUKMOK KA NALANG SA BAHAY NIYO ",
    "TANGINA WALA NA? ",
    "HOY TANGA LUMAPAG KA HAHA ",
    "TANGINAMO KA PALAKAS KAPA SLOW TYPER ",
    "HOY BOBO FLO FLOOD KITA TANGA ",
    "WALA KA EA MO SAKIN NA ",
    "BATUKAN LANG KITA ",
    "LUI ON TOP BOBO ",
    "KILALANIN MO BINABANGGA MO BOBO ",
    "TANDAAN MO AKO BOSS AMO MO ",
    "KAKATAYIN KO LANG ANG PAMILYA MO ",
    "D.O KANA TANGINAMO SLOW TYPER ",
    "ISA KANG ABNORMAL NA TAO",
    "REMEMBER MY NAME TANGA",
    "WALA KA EA MO SAKIN NA",
    "WALA KA NAMAN PALA E",
    "AKO ANG BOSS AMO MO",
    "LESSON AND LEARN WAG MAGING TANGA",
    "PAG KAKANTUTIN KITA 24/7",
    "SAN KANA BOBO",
    "SUMABAY KA TANGA",
    "HINAHATAK LANG KITA SA KAILALIMAN",
    "BOBO KA HAHA DI KA TATAGOS",
    "LESSON AND LEARN WAG MAGING TANGA",
    "TANGINAMONG MALNOURISHED KA"
]

GIF_URL = "https://media.giphy.com/media/er1hbOdwxCdzcmf034/giphy.gif"

app = Flask(__name__)
@app.route('/')
def home():
    return "5 Bots are running!"
@app.route('/health')
def health():
    return "OK"
def run_flask():
    app.run(host='0.0.1.0', port=5000)
flask_thread = threading.Thread(target=run_flask)
flask_thread.daemon = True
flask_thread.start()

all_active_rants = {}
all_user_sessions = {}
all_clients = {}

def bold_text(text):
    return f"**{text}**"

def strikethrough(text):
    return f"~~{text}~~"

def get_random_emoji():
    return random.choice(["🫵🤮🤮🤣🤡"])

async def create_mention(name, user):
    try:
        return f"[{name}](tg://user?id={user.id})"
    except:
        try:
            return f"[{name}](tg://user?id={user})"
        except:
            return name

async def get_user_by_id(user_id, client):
    try:
        user_id = int(user_id)
        try:
            user = await client.get_entity(user_id)
            return user
        except ValueError:
            class MinimalUser:
                def __init__(self, user_id):
                    self.id = user_id
                    self.first_name = f"User{user_id}"
                    self.username = None
                    self.bot = False
            return MinimalUser(user_id)
        except Exception as e:
            return None
    except:
        return None

async def get_chat_entity(chat_input, client):
    try:
        if chat_input.replace('-', '').isdigit():
            chat_id = int(chat_input)
            return await client.get_entity(chat_id)
        elif chat_input.startswith('@'):
            return await client.get_entity(chat_input)
        else:
            return await client.get_entity(chat_input)
    except Exception as e:
        return None

async def is_bot_in_chat(chat_entity, client):
    try:
        if not isinstance(chat_entity, (Channel, Chat)):
            return True
        me = await client.get_me()
        try:
            participants = await client.get_participants(chat_entity, limit=50)
            for participant in participants:
                if participant.id == me.id:
                    return True
            return False
        except:
            try:
                test_msg = await client.send_message(chat_entity, "Testing bot access...")
                await test_msg.delete()
                return True
            except:
                return False
    except Exception as e:
        return False

async def handle_ping(event, bot_name):
    try:
        await event.reply(f"✅ {bot_name} is alive and responsive!")
    except:
        pass

async def handle_help(event, bot_name):
    help_text = f"""
🤖 **{bot_name} - Auto Spam Rant Bot Help**

**Commands:**
• `.asr` - Start interactive auto spam rant setup
• `.stoprant` - Stop current rant
• `.asrhelp` - Show this help
• `.ping` - Test if bot is responsive

**Multi-Target Support:**
• Max 3 targets per rant
• Separate mention words for each target
• Works with user IDs and usernames

**Works in:** Groups & Private chats
"""
    try:
        await event.reply(help_text)
    except:
        pass

async def handle_stop_rant(event, bot_config, active_rants):
    if event.sender_id not in bot_config['authorized_users']:
        return
    
    chat_id = event.chat_id
    if chat_id in active_rants:
        active_rants[chat_id] = False
        try:
            msg = await event.reply("✅ Auto spam rant stopped!")
            await asyncio.sleep(2)
            await msg.delete()
        except:
            pass
    else:
        try:
            msg = await event.reply("❌ No active auto spam rant here")
            await asyncio.sleep(2)
            await msg.delete()
        except:
            pass

async def start_asr_session(event, bot_config, user_sessions):
    user_id = event.sender_id
    user_sessions[user_id] = {
        'step': 1,
        'data': {},
        'chat': event.chat_id
    }
    
    await event.reply("🤖 **Auto Spam Rant Setup**\n\nWhere should I rant? (Enter group ID with - or group username with @)\nExample: -100123456789 or @groupusername\n\nType `cancel` to stop setup.")

async def handle_session_messages(event, bot_config, user_sessions, active_rants, client):
    if event.sender_id not in bot_config['authorized_users']:
        return
    
    user_id = event.sender_id
    message = event.text.strip()
    
    if user_id not in user_sessions:
        return
    
    session = user_sessions[user_id]
    
    if message.lower() == 'cancel':
        del user_sessions[user_id]
        await event.reply("❌ Setup cancelled.")
        return
    
    if session.get('step') == 5 and message:
        chat_id = session['data']['target_chat']
        if chat_id in active_rants:
            active_rants[chat_id] = False
            await event.reply("🛑 Ranting stopped!")
            del user_sessions[user_id]
        return
    
    try:
        if session['step'] == 1:
            chat_entity = await get_chat_entity(message, client)
            if not chat_entity:
                await event.reply("❌ Invalid group! Please enter a valid group ID or username.\nExample: -100123456789 or @groupusername")
                return
            
            if not await is_bot_in_chat(chat_entity, client):
                await event.reply("❌ I'm not a member of that group! Add me to the group first.")
                del user_sessions[user_id]
                return
            
            session['data']['target_chat'] = chat_entity.id
            session['step'] = 2
            
            chat_title = getattr(chat_entity, 'title', f"Chat {chat_entity.id}")
            await event.reply(f"✅ Group set: {chat_title}\n\nHow many users do you want to target? (1-3)\nExample: 2")
            
        elif session['step'] == 2:
            if not message.isdigit() or not (1 <= int(message) <= 3):
                await event.reply("❌ Please enter a number between 1 and 3!")
                return
            
            target_count = int(message)
            session['data']['target_count'] = target_count
            session['step'] = 3
            session['data']['targets'] = []
            session['data']['current_target'] = 1
            
            await event.reply(f"✅ Targeting {target_count} user(s)\n\nEnter target #{1} (User ID or username):\nExample: 123456789 or @username")
            
        elif session['step'] == 3:
            current_target = session['data']['current_target']
            target_count = session['data']['target_count']
            
            target_user = None
            if message.isdigit():
                target_user = await get_user_by_id(message, client)
            elif message.startswith('@'):
                try:
                    target_user = await client.get_entity(message)
                except:
                    target_user = None
            else:
                await event.reply("❌ Invalid format! Please enter a valid user ID (numbers only) or @username.")
                return
            
            if not target_user:
                await event.reply("❌ Invalid target! Please enter a valid user ID or username.\nExample: 123456789 or @username")
                return
            
            session['data']['targets'].append(target_user)
            
            if current_target < target_count:
                session['data']['current_target'] += 1
                await event.reply(f"✅ Target #{current_target} set!\n\nEnter target #{current_target + 1} (User ID or username):\nExample: 123456789 or @username")
            else:
                session['step'] = 4
                session['data']['current_mention'] = 1
                
                if target_count == 1:
                    await event.reply("✅ All targets set!\n\nEnter mention word for target #1 (can contain spaces):")
                else:
                    await event.reply(f"✅ All targets set!\n\nEnter mention word for target #1:")
            
        elif session['step'] == 4:
            current_mention = session['data']['current_mention']
            target_count = session['data']['target_count']
            
            if not message.strip():
                await event.reply("❌ Mention word cannot be empty!")
                return
            
            if 'mention_words' not in session['data']:
                session['data']['mention_words'] = []
            
            session['data']['mention_words'].append(message.strip())
            
            if current_mention < target_count:
                session['data']['current_mention'] += 1
                await event.reply(f"✅ Mention word #{current_mention} set!\n\nEnter mention word for target #{current_mention + 1}:")
            else:
                session['step'] = 5
                
                await event.reply("✅ Setup complete! Starting auto rant...\n\nSend any message to stop ranting.")
                
                chat_id = session['data']['target_chat']
                targets = session['data']['targets']
                mention_words = session['data']['mention_words']
                
                mentions = []
                for i, target in enumerate(targets):
                    mention = await create_mention(mention_words[i], target)
                    mentions.append(mention)
                
                active_rants[chat_id] = True
                count = 0
                
                while active_rants.get(chat_id, False):
                    count += 1
                    insult = random.choice(VZKOU_INSULTS)
                    
                    if len(mentions) == 1:
                        message_text = f"{strikethrough(bold_text(insult))} {strikethrough(bold_text(mentions[0]))} {get_random_emoji()} [{count}]"
                    else:
                        combined_mentions = " ".join([strikethrough(bold_text(m)) for m in mentions])
                        message_text = f"{strikethrough(bold_text(insult))} {combined_mentions} {get_random_emoji()} [{count}]"
                    
                    try:
                        await client.send_message(
                            chat_id,
                            message_text,
                            file=GIF_URL,
                            link_preview=False
                        )
                    except Exception as e:
                        active_rants[chat_id] = False
                        await event.reply(f"❌ Error sending message: {e}")
                        break
                    
                    await asyncio.sleep(2)
                
                if user_id in user_sessions:
                    del user_sessions[user_id]
                
    except Exception as e:
        if user_id in user_sessions:
            del user_sessions[user_id]

async def setup_bot(bot_config):
    client = TelegramClient(
        session=bot_config['session_name'],
        api_id=bot_config['api_id'],
        api_hash=bot_config['api_hash'],
        connection_retries=10,
        auto_reconnect=True,
        timeout=60,
        request_retries=5
    )
    
    bot_active_rants = {}
    bot_user_sessions = {}
    
    all_active_rants[bot_config['name']] = bot_active_rants
    all_user_sessions[bot_config['name']] = bot_user_sessions
    all_clients[bot_config['name']] = client
    
    @client.on(events.NewMessage(pattern=r'^(\.asr|\.stoprant|\.asrhelp|\.ping)'))
    async def handle_commands(event):
        if event.sender_id not in bot_config['authorized_users']:
            return
        
        try:
            command = event.text.split()[0]
            
            if command == '.ping':
                await handle_ping(event, bot_config['name'])
            elif command == '.asrhelp':
                await handle_help(event, bot_config['name'])
            elif command == '.stoprant':
                await handle_stop_rant(event, bot_config, bot_active_rants)
            elif command.startswith('.asr'):
                await start_asr_session(event, bot_config, bot_user_sessions)
        except Exception as e:
            pass
    
    @client.on(events.NewMessage)
    async def handle_messages(event):
        await handle_session_messages(event, bot_config, bot_user_sessions, bot_active_rants, client)
    
    max_retries = 10
    retry_delay = 30
    
    for attempt in range(max_retries):
        try:
            await client.start(bot_token=bot_config['bot_token'])
            me = await client.get_me()
            print(f"✅ {bot_config['name']} started successfully!")
            print(f"   🤖 Username: @{me.username}")
            print(f"   🆔 ID: {me.id}")
            
            while True:
                await asyncio.sleep(300)
                try:
                    await client.get_me()
                except (ConnectionError, OSError):
                    print(f"❌ {bot_config['name']} connection lost, reconnecting...")
                    try:
                        await client.disconnect()
                    except:
                        pass
                    await asyncio.sleep(5)
                    await client.start(bot_token=bot_config['bot_token'])
                    print(f"✅ {bot_config['name']} reconnected!")
                    
        except (ConnectionError, OSError) as e:
            print(f"❌ {bot_config['name']} connection error (attempt {attempt + 1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                print(f"⏳ {bot_config['name']} retrying in {retry_delay} seconds...")
                await asyncio.sleep(retry_delay)
                retry_delay *= 2
            else:
                print(f"❌ {bot_config['name']} max retries reached.")
                break
        except Exception as e:
            print(f"❌ {bot_config['name']} unexpected error: {e}")
            break
    
    await client.run_until_disconnected()

async def main():
    print("🚀 Starting 5 Auto Spam Rant Bots...")
    
    tasks = []
    for bot_config in BOT_CONFIGS:
        task = asyncio.create_task(setup_bot(bot_config))
        tasks.append(task)
    
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    asyncio.run(main())